#!/bin/bash
# Testing , delete arp cache for IP Address
# sudo arp -d 192.168.1.101
MacAddress="b8:27:eb:67:ae:53"
RaspberryPiIP=$(arp -na | grep -i $MacAddress | tail -1 | awk '{print $2}' | cut -d "(" -f2 | cut -d ")" -f1)
if [ -z "$RaspberryPiIP" ]; then
	echo "arp scan empty"
	if [[ "$OSTYPE" == "linux-gnu" ]]; then
		DefaultGateway=$(netstat -rn -A inet | grep -A 1 "Gateway" | tail -1 | awk '{print $2}')
		echo "Default Gateway = $DefaultGateway"
		echo "nmaping Default Gateway ..."
		RaspberryPiIP=$(sudo nmap -sn $DefaultGateway/24 | grep -i '$MacAddress' -B 2 | head -1 | awk '{print $(NF)}')		
	elif [[ "$OSTYPE" == "darwin"* ]]; then
		netstat -rn -A inet | while read line;
		do
			type=$(echo $line | awk '{print $1;}')
			if [ "$type"  == "default" ]; then
				gateway=$(echo $line | awk '{print $2;}')
				RaspberryPiIP=$(sudo nmap -sn $gateway/24 | grep -i '$MacAddress' -B 2 | head -1 | awk '{print $(NF)}')
			fi
		done
		#DefaultGateway=$(ip route ls | grep default | awk '{print $3}')
	fi
fi
if [ -z "$RaspberryPiIP" ]; then
	RaspberryPiIP=$(arp -na | grep -i $MacAddress | tail -1 | awk '{print $2}' | cut -d "(" -f2 | cut -d ")" -f1)
fi
echo "Raspberry Pi IP = $RaspberryPiIP"
sshpass -p lamorsa ssh morphs@$RaspberryPiIP -AY -o ServerAliveInterval=60 -o StrictHostKeyChecking=no
#sshpass -p raspberry ssh pi@$RaspberryPiIP -AY -o ServerAliveInterval=60 -o StrictHostKeyChecking=no
