#!/bin/bash
dirname=$(dirname "$1")
basename=$(basename "$1" | cut -d. -f1)
outputpath=$(echo "$dirname"/"$basename-BG-WHITE".gif)
mkdir /tmp/add-white-background-to-gif-5756124
echo "Inflating GIF"
convert "$1" /tmp/add-white-background-to-gif-5756124/frame-%06d.gif
for file in /tmp/add-white-background-to-gif-5756124/*
do
	extension=$(echo "$file" | sed 's/^.*\.//')
	if [ "$extension" = "gif" ]; then
		echo "Adding White Background to : $file"
		mogrify -background white -flatten -format gif "$file"
	fi
done
echo "Rejoining GIF Frames"
convert /tmp/add-white-background-to-gif-5756124/frame-* "$outputpath"
rm -rf /tmp/add-white-background-to-gif-5756124
