#!/bin/bash
# brew install whisper-cpp
ffmpeg -i "$1" -ar 16000 -ac 1 output.wav
sleep 1
whisper-cpp -t 12 --language en --model /Users/morpheous/APPLICATIONS_2/whisper.cpp/models/ggml-small.en-q5_1.bin --file output.wav | tee output.txt
