#!/usr/bin/env node

const process = require("process");
const path = require("path");
const child = require("child_process");
let base_path = child.spawnSync( 'npm', [ 'root' , '-g' ] , { encoding: 'utf8' } );
base_path = base_path.stdout.trim();
const base91 = require( path.join( base_path ,  "base91" ) );
const input = process.argv[ 2 ];
console.log( input );
console.log( base91.encode( input ) );
