#!/usr/bin/env python3
import sys
import bcrypt
import pyperclip
import base64
def base64_encode( message ):
	try:
		message_bytes = message.encode( 'utf-8' )
		base64_bytes = base64.b64encode( message_bytes )
		base64_message = base64_bytes.decode( 'utf-8' )
		return base64_message
	except Exception as e:
		print( e )
		return False

salt = bcrypt.gensalt( rounds=16 )
result = bcrypt.hashpw( bytes( sys.argv[ 1 ] , encoding="raw_unicode_escape" ) , salt ).decode( "utf8" )
print( result )
print( "Base64 Encoded ===" , base64_encode( result ) )
pyperclip.copy( result )
