#!/usr/bin/env python3
import sys
import bcrypt
import pyperclip
import base64
def base64_decode( base64_message ):
	try:
		base64_bytes = base64_message.encode( 'utf-8' )
		message_bytes = base64.b64decode(base64_bytes)
		message = message_bytes.decode( 'utf-8' )
		return message
	except Exception as e:
		print( e )
		return False

plaintext_password = sys.argv[ 1 ]
hashed_password_b64 = sys.argv[ 2 ]
hashed_password = base64_decode( hashed_password_b64 )
print( plaintext_password ) 
print( hashed_password_b64 ) 
print( hashed_password ) 

salt = bcrypt.gensalt( rounds=16 )
hashed = bcrypt.hashpw( bytes( plaintext_password , encoding="raw_unicode_escape" ) , salt )
print( hashed )
result = bcrypt.checkpw( bytes( plaintext_password , encoding="raw_unicode_escape" ) , bytes( hashed_password , encoding="raw_unicode_escape" ) )
print( result )
pyperclip.copy( result )
