#!/bin/bash
# https://caddyserver.com/docs/caddyfile/directives/basicauth
username=$(pwgen -1 $1 | shasum -a 256 | awk '{ print $1; }' | head -c 20 )
password=$(pwgen -1 $1 | shasum -a 256 | awk '{ print $1; }' | head -c 20 )
echo "Username === $username"
echo "Password === $password"
bcrypted_password=$(htpasswd -nbBC 10 $username $password)
echo "Bcrypted Password === $bcrypted_password"
