#!/bin/bash
AudioCodec=$(ffprobe "$1" 2>&1 >/dev/null | grep Stream.*Audio | sed -e 's/.*Audio: //' -e 's/[, ].*//')
VideoCodec=$(ffprobe "$1" 2>&1 >/dev/null | grep Stream.*Video | sed -e 's/.*Video: //' -e 's/[, ].*//')
echo "Audio Codec = $AudioCodec"
echo "Video Codec = $VideoCodec"
