#!/usr/bin/env python3
import os
import sys
from pathlib import Path
import subprocess

# https://stackoverflow.com/questions/803265/getting-realtime-output-using-subprocess
def run_bash_command( options ):
	try:
		print( options )
		result = subprocess.Popen( options , cwd=os.getcwd() , close_fds=True , shell=True , universal_newlines=True , stdout=subprocess.PIPE , stderr=subprocess.PIPE )
		captured_output = ""
		while result.poll() is None:
			out = result.stdout.read(1)
			if out == '':
				break
			sys.stdout.write( out )
			sys.stdout.flush()
			captured_output += out
		return captured_output
	except Exception as e:
		print( e )
		return False

if __name__ == "__main__":
	input_fp = Path( sys.argv[ 1 ] )
	input_fp_absolute = input_fp.resolve()
	input_file_extension = input_fp.suffix
	output_fp = input_fp.parent.joinpath( f"{input_fp.stem}.mp4" )
	output_fp_absolute = output_fp.resolve()

	# 1.) Get Codec Info
	codec_info = run_bash_command([ f'ffprobe "{input_fp_absolute}" 2>&1 >/dev/null' ])
	try:
		audio_codec = codec_info.split( "Audio: " )[ 1 ].split( "," )[ 0 ].strip()
	except Exception as e:
		audio_codec = ""
		print( e )
	try:
		video_codec = codec_info.split( "Video: " )[ 1 ].split( " " )[ 0 ].strip()
	except Exception as e:
		video_codec = ""
		print( e )
	print( audio_codec , video_codec )

	# 2.) Convert To Video=H264 , Audio=AAC
	if video_codec != "h264" and audio_codec != "aac":
		run_bash_command([ f'ffmpeg -i "{input_fp_absolute}" -c:v libx264 -c:a aac -strict -2 "{output_fp_absolute}"' ])
	elif video_codec != "h264" and audio_codec == "aac":
		run_bash_command([ f'ffmpeg -i "{input_fp_absolute}" -c:v libx264 -c:a copy -strict -2 "{output_fp_absolute}"' ])
	elif video_codec == "h264" and audio_codec != "aac":
		run_bash_command([ f'ffmpeg -i "{input_fp_absolute}" -c:v copy -c:a aac -strict -2 "{output_fp_absolute}"' ])
	elif video_codec == "h264" and audio_codec == "aac":
		run_bash_command([ f'ffmpeg -i "{input_fp_absolute}" -c:v copy -c:a copy -strict -2 "{output_fp_absolute}"' ])
	else:
		print( "???" )