#!/usr/bin/env python3
import sys
from pathlib import Path
from pprint import pprint
from PIL import Image

def get_images():
	ALLOWED_EXTENSIONS = [ ".jpeg" , ".jpg" , ".png" ]
	BaseDirectoryPosixPath = Path( sys.argv[1] if len(sys.argv) > 1 else Path.cwd() )
	FilesPosixInBaseDirectory = BaseDirectoryPosixPath.glob( '*' )
	FilesPosixInBaseDirectory = [ x for x in FilesPosixInBaseDirectory if x.is_file() ]
	return [ Image.open( str( x ) ) for x in FilesPosixInBaseDirectory if x.suffix in ALLOWED_EXTENSIONS ]

# https://www.blog.pythonlibrary.org/2021/06/23/creating-an-animated-gif-with-python/
if __name__ == "__main__":
	frames = get_images()
	frame_one = frames[0]
	frame_one.save( "animation.gif" ,
		format = "GIF" ,
		append_images = frames ,
		save_all = True ,
		duration = int( sys.argv[2] ) if len(sys.argv) > 2 else 100 ,
		loop = 0
	)

# rm /tmp/convertImagesInDirectorytoGIF.txt || export wadu="wadu"
# for file in "$1"; do
# 	echo "$file"
# done
#for i in $(seq 1 $2); do echo "file '$1'" >> list.txt; done
#ffmpeg -f concat -i list.txt -c copy "$1 - combined.mp4"
#rm list.txt