#!/usr/bin/env python3
from PIL import Image
import sys
import warnings
from pathlib import Path
warnings.filterwarnings( "ignore" , "(Possibly )?corrupt EXIF data" , UserWarning )
input_file_path = Path( sys.argv[ 1 ] )
im = Image.open( sys.argv[1] )
output_path = f"{input_file_path.resolve().parent}/{input_file_path.stem}.jpg"
im.save( output_path , 'JPEG' )
