#!/bin/bash
sudo docker images | grep none | awk '{ print $3; }' | xargs sudo docker rmi -f
echo yes | sudo docker image prune -a
sudo docker rmi $(sudo docker images -a --filter='dangling=true' -q) -f
sudo docker rmi $(sudo docker images | grep '^<none' | awk '{print $3}')
sudo docker rmi $(sudo docker images | grep "none" | awk '{print $3}')
sudo docker kill $(sudo docker ps -q)
sudo docker rm $(sudo docker ps --filter='status=exited' --filter='status=created' -q)
sudo docker rmi $(sudo docker images -a -q)
