#!/bin/bash

sudo pkill -SIGHUP -f /Applications/Docker.app 'docker serve'
sudo pkill -SIGHUP -f "com.docker.vmnetd"
sudo pkill -SIGHUP -f "com.docker.vpnkit"
sudo pkill -SIGHUP -f "com.docker.dev-envs"

# sudo launchctl disable system/com.docker.vmnetd
# sudo rm -f /Library/LaunchDaemons/com.docker.vmnetd.plist
# sudo rm -f /Library/PrivilegedHelperTools/com.docker.vmnetd
