#!/usr/bin/env python3
# https://github.com/ShayHill/docx2python
import sys
from pathlib import Path
from docx2python import docx2python
image_output_directory_posix = Path.cwd().joinpath( "images" )
image_output_directory_posix.mkdir( parents=True , exist_ok=True )
docx2python( sys.argv[1] , str( image_output_directory_posix ) )

