#!/bin/bash

# https://www.howtogeek.com/248489/how-to-add-custom-ringtones-to-your-iphone/
# https://stackoverflow.com/questions/16374028/unable-to-convert-mp3-to-m4a-using-ffmpeg
# https://superuser.com/questions/370625/ffmpeg-command-to-convert-mp3-to-aac

mkdir outputs
for f in *.mp3; do ffmpeg -i "$f" -c:a aac  -vn "outputs/${f%.mp3}.m4a"; done

# then rename all to .m4r
