#!/bin/bash

# about:profiles
# /Applications/Firefox.app/Contents/MacOS/firefox-bin -P
# https://www.ghacks.net/2017/10/08/the-most-important-firefox-command-line-options/
# /Applications/Firefox.app/Contents/MacOS/firefox-bin -P "WinStitch23" --browser &

# http://sonnygill.net/mac/mac-multiple-firefox-profiles/
/Applications/Firefox.app/Contents/MacOS/firefox-bin -P "WinStitch23" -no-remote &> /dev/null &
