#!/bin/bash
pwgen -1 34 | shasum -a 256 | awk '{ print $1; }' | while read x ; do echo "${x:0:32}" ; echo "${x:32:64}" ; done && pwgen -1 34 | shasum -a 256 | awk '{ print $1; }' && pwgen -1 34 | shasum -a 256 | awk '{ print $1; }'
a=$(od -A n -t d -N 10 /dev/urandom | tr -ds ' ' '\n')
b=$(od -A n -t d -N 10 /dev/urandom | tr -ds ' ' '\n')
# https://stackoverflow.com/a/56649302
abs() { 
    [[ $[ $@ ] -lt 0 ]] && echo "$[ ($@) * -1 ]" || echo "$[ $@ ]"
}
n1=$(abs a)
n2=$(abs b)
echo "$n1" | cut -c 1-10
echo "$n2" | rev | cut -c 1-10
