#!/bin/bash
ssh -D 8282 -f -C -q -N -o IdentitiesOnly=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=60 -o LogLevel=ERROR  -F /dev/null -i /Users/$LOCAL_USERNAME/.ssh/$LINUX_MISC_PRIVATE_KEY $LINUX_MISC_USER@$LINUX_MISC_IP
