#!/bin/bash

#RaspberryPiIP=$(arp -na | grep "b8:27:eb:67:ae:53" | awk '{print $2}' | cut -d "(" -f2 | cut -d ")" -f1)
RaspberryPiIP=$(/usr/local/bin/findLocalClientByMacAddress "b8:27:eb:67:ae:53" )
echo $RaspberryPiIP
sshpass -p lamorsa ssh pi@$RaspberryPiIP -AY -o ServerAliveInterval=60
