#!/usr/bin/env python3
# pip install pyyaml
import yaml
import sys
from pathlib import Path

def read_yaml( file_path ):
	with open( file_path ) as f:
		return yaml.safe_load( f )

def write_text( file_path , text_lines_list ):
	with open( file_path , 'w', encoding='utf-8' ) as f:
		f.writelines( text_lines_list )

input_yaml_file_path = sys.argv[ 1 ]
links = read_yaml( input_yaml_file_path )
for title , url in links.items():
	write_text( str( Path.cwd().joinpath( f"{title}.url" ) ) , [ "[InternetShortcut]\n" , f"URL={url[0]}\n" ] )
