#!/usr/bin/env python3
# Because why would anybody every need these in bash
# " ! " # $ & ' ( ) * , ; < > ? [ \ ] ^ ` { | }"
# https://stackoverflow.com/a/27817504
import pyperclip
password = f" ! \" # $ & ' ( ) * , ; < > ? [ \ ] ^ ` { | }"
print( password )
pyperclip.copy( password )