#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import re
import sys
from pipreqs.pipreqs import main
if __name__ == '__main__':
	sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
	if len( sys.argv ) < 2:
		sys.argv.append( "." )
	if len( sys.argv ) < 3:
		sys.argv.append( "--no-pin" )
		sys.argv.append( "--force" )
	sys.exit(main())
