#!/usr/bin/env python3
import sys
import pptx

powerpoint = pptx.Presentation( sys.argv[1] )
print( powerpoint )
for slide_index , slide in enumerate( powerpoint.slides ):
	print( f"Processing Slide [{slide_index+1}] of {len(powerpoint.slides)}" )
	for shape_index , shape in enumerate( slide.shapes ):
		print( f"\tProcessing Shape [{shape_index+1}] of {len(slide.shapes)}" )
		print( f"\t\tShape Type === {shape.shape_type}" )
		if hasattr( shape , "image" ):
			#print( shape.image.content_type )
			image = shape.image
			image_bytes = image.blob
			image_filename = f"image-{slide_index}-{shape_index}.jpeg"
			with open( image_filename , "wb" ) as f:
				f.write( image_bytes )