#!/usr/bin/env python3
import sys
from pyzbar.pyzbar import decode
from PIL import Image
image_data = Image.open( sys.argv[1] )
result = decode( image_data )
text = result[ 0 ].data
text = text.decode( "utf-8" )
print( text )
