#!/usr/bin/env python

import os
import sys
import random

if len( sys.argv ) < 1:
	password_length = 25
else:
	password_length = int( sys.argv[ 1 ] )

def get_semi( length ):
	return os.popen( "/usr/local/bin/pwgen -s -1 -y " + str( length ) ).read().strip()

iterations = random.randrange( 100 , 300 )
buffer = ""
for i in range( 0 , iterations ):
	buffer += get_semi( password_length )

#print( buffer )
#buffer_length = len( buffer )
#print( str( buffer_length ) )
#start = random.randrange( buffer_length - password_length )
#print( str( start ) )
#stop = random.randrange( start , start + password_length )
#print( str( stop ) )
substring = buffer[ 0:password_length ]
print( substring )
