#!/bin/bash
rclone -P copy --update \
"/Users/morpheous/WORKSPACE" \
"PDB636597OneDrive:WORKSPACE/MINI/"
--exclude *.DS_Store \
--exclude *node_modules/** \
--exclude *venv/** \
--create-empty-src-dirs
