#!/usr/bin/env python3

import sys
import math
angle_degrees = float( sys.argv[1] )

print( f"Sine of {angle_degrees}° === {math.sin(math.radians(angle_degrees))} ° === {math.sin(angle_degrees)} Radians" )
print( f"Cosine of {angle_degrees}° === {math.cos(math.radians(angle_degrees))} ° === {math.cos(angle_degrees)} Radians" )
print( f"Tan of {angle_degrees}° === {math.tan(math.radians(angle_degrees))} ° === {math.tan(angle_degrees)} Radians" )

print("")

try:
	print( f"Arc Sine of {angle_degrees}° === {math.asin(math.radians(angle_degrees))} ° === {math.asin(angle_degrees)} Radians" )
except Exception as e:
	pass
try:
	print( f"Arc Cosine of {angle_degrees}° === {math.acos(math.radians(angle_degrees))} ° === {math.acos(angle_degrees)} Radians" )
except Exception as e:
	pass

try:
	print( f"Arc Tan of {angle_degrees}° === {math.atan(math.radians(angle_degrees))} ° === {math.atan(angle_degrees)} Radians" )
except Exception as e:
	pass