#!/usr/bin/bash

# 1.) Prep
title=$(youtube-dl --verbose -e "$1")
input_file=$(echo "$title".mkv)
output_file=$(echo "$title".mp4)
output_file_temp=$(echo "$title"_temp.mp4)
echo $input_file
echo $output_file

# 2.) Download via YoutubeDL
youtube-dl "$1" -o "$title"


# 3.) Convert to "streaming" MP4
AudioCodec=$(ffprobe "$input_file" 2>&1 >/dev/null | grep Stream.*Audio | sed -e 's/.*Audio: //' -e 's/[, ].*//')
VideoCodec=$(ffprobe "$input_file" 2>&1 >/dev/null | grep Stream.*Video | sed -e 's/.*Video: //' -e 's/[, ].*//')
[ -z "$VideoCodec" ] && continue;
[ -z "$AudioCodec" ] && continue;
echo "Current Audio Codec = $AudioCodec"
echo "Current Video Codec = $VideoCodec"
if [ "$VideoCodec" != "h264" ] && [ "$AudioCodec" != "aac" ]; then
	echo "ReEncoding Video and Audio"
	echo "New Filename = $output_file_temp"
	ffmpeg -i "$input_file" -c:v libx264 -c:a aac -strict -2 "$output_file_temp"
elif [ "$VideoCodec" != "h264" ] && [ "$AudioCodec" = "aac" ]; then
	echo "ReEncoding Video"
	echo "New Filename = $output_file_temp"
	ffmpeg -i "$input_file" -c:v libx264 -c:a copy -strict -2 "$output_file_temp"
elif [ "$VideoCodec" = "h264" ] && [ "$AudioCodec" != "aac" ]; then
	echo "ReEncoding Audio"
	echo "New Filename = $output_file_temp"
	ffmpeg -i "$input_file" -c:v copy -c:a aac -strict -2 "$output_file_temp"
elif [ "$VideoCodec" = "h264" ] && [ "$AudioCodec" = "aac" ]; then
	if [ "$extension" = "mp4" ]; then
		echo "Skipping, Already MP4 With Correct Audio and Video Codecs"
		echo ""
		continue
	else
		echo "Copying Video and Audio"
	fi
	echo "$output_file_temp"
	ffmpeg -i "$input_file" -c:v copy -c:a copy -strict -2 "$output_file_temp"
fi
rm "$input_file"
mv "$output_file_temp" "$output_file"
echo ""
